title: Econblog
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:" 

 My name is Elena Stolpovsky. I live in Washington State and have a PhD in Economics with a focus in Labor Economics. I worked as an economist in a clean tech startup [AquaRing Energy](https://www.linkedin.com/company/aquaring-energy/about/) that is developing innovative technology, including a wave energy generation technology.
 My PhD thesis was about household decision making and the roles of the household members in the decision-making process. If you are curious, you can access the whole thesis (!) [here] (https://rucore.libraries.rutgers.edu/rutgers-lib/51472/PDF/1/play/)
 Please connect with me on [LinkedIn](linkedin.in/estolpovsky) with any research ideas or to chat about current events, economics and society,
#social sites
github_username:  https://github.com/elenas70 # DO NOT include the @ character, or else the build will fail!
linkedin: https://www.linkedin.com/in/estolpovsky/
show_excerpts: true # set to false to remove excerpts on the homepage
