github:
  is_project_page: false
title: <img src="avatar.PNG" style="width:50%" class="inline"/> <br> <a href="https://www.linkedin.com/in/estolpovsky/"><font size="4"> Elena Stolpovsky </font> </a> <br> <font size="3"> Researcher, PhD Economist  </font>
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  Welcome to my blog. My name is Elena Stolpovsky. I am interested in economics, society and technology.
  <br>As a graduate student I researched <a href="https://rucore.libraries.rutgers.edu/rutgers-lib/51472/">economic decision-making of househoods</a> - a topic that fascinates me, for some reason, but is not very popular or applicable.
  Check out my <a href="https://rucore.libraries.rutgers.edu/rutgers-lib/51472/">my thesis</a>, and let me know what you think.
  <br>I worked in the energy industry and became passionate about sustainability in energy generation and economic development.
  <br>Please <a href = "mailto: estolpovsky@gmail.com"> email me</a> with questions or research ideas or leave a comment on my post!
  
#social sites
show_excerpts: true # set to false to remove excerpts on the homepage
