github:
  is_project_page: false
title: <img src="avatar.PNG" style="width:50%" class="inline"/> <br> <font size="5"> Elena Stolpovsky </font> <br> <font size="4"> Researcher, PhD Economist  </font>
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  Welcome to my blog. My name is Elena Stolpovsky. I am interested in economics, society and technology.
  <br>As a graduate student I researched economic decision-making of househoods - a topic that fascinates me, for some reason, but is not very popular or applicable.
  Please check out my <a href="https://rucore.libraries.rutgers.edu/rutgers-lib/51472/">my thesis</a>, and let me know what you think.
  <br>I worked in the energy industry and became passionate about sustainability in energy generation and economic development.
  
#social sites
show_excerpts: true # set to false to remove excerpts on the homepage
