title: <font size="5"> Elena Stolpovsky </font> <br> <font size="4"> PhD Economist  </font>
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  Welcome to my blog. My name is Elena Stolpovsky. I am interested in economics, society and technology.
  <br>As a graduate student I researched economic decision-making of househoods - a topic that fascinates me, for some reason, but is not very popular or applicable.
  You are free to check out my <a href="https://rucore.libraries.rutgers.edu/rutgers-lib/51472/">my thesis</a>, and let me know what you think.
  <br>I worked in the energy industry and became passionate about sustainable energy generation and sustainable development in general.
  <br>I currently am currently engaged in independent research and work on ad-hoc projects. Connect with me on <a href="https://www.linkedin.com/in/estolpovsky/">LinkedIn</a> with comments about my blog, research ideas and project suggestions!
#social sites
github_username:  https://github.com/elenas70 # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
