title: <font size="5"> About Me </font>
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  I have a PhD in Economics. My thesis is about economic decision-making of househoods - a topic that fascinates me, for some reason, but is not very popular or applicable.
  I have a link to my thesis on this blog in case someone has a similar fascination or is curious.
  I worked in the energy industry and became passionate about sustainable energy generation.
  Connect with me on LinkedIn with comments about my blog, research ideas and project suggestions!
#social sites
github_username:  https://github.com/elenas70 # DO NOT include the @ character, or else the build will fail!
linkedin: https://www.linkedin.com/in/estolpovsky/
show_excerpts: true # set to false to remove excerpts on the homepage
