title: Econblog
theme: jekyll-theme-minimal
author: Elena Stolpovsky
email: estolpovsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have a PhD in Economics focusing on Labor Economics. I am following the recent developments in U.S. economy and the impact of COVID on the labor market. The studies use the Current Population Survey administered by the Census Bureau. 
 
# social links
github_username:  https://github.com/elenas70 # DO NOT include the @ character, or else the build will fail!
linkedin: https://www.linkedin.com/in/estolpovsky/
show_excerpts: true # set to false to remove excerpts on the homepage
